---
apiVersion: v1
kind: Service
metadata:
  name: goof-mongo
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    app: goof-mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goof-mongo
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: goof-mongo
  template:
    metadata:
      labels:
        app: goof-mongo
    spec:
      containers:
      - image: mongo
        name: goof-mongo
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
    
